# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    banner: true
    db-config:
      id-type: auto
      insert-strategy: not_empty
      where-strategy: not_empty
      update-strategy: ignored
  configuration:
    jdbc-type-for-null: null
    call-setters-on-nulls: true
    shrink-whitespaces-in-sql: true
    # mybatis-plus配置控制台打印完整带参数SQL语句
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 搜索指定包别名
  typeAliasesPackage: com.breeze.**.entity