DROP
DATABASE IF EXISTS `breeze`;
CREATE
DATABASE  `breeze` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP
DATABASE IF EXISTS `breeze_flowable`;
CREATE
DATABASE  `breeze_flowable` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
