server:
  port: 9000

spring:
  messages:
    basename: i18n/message
    encoding: UTF-8
  # json提交时 [Date Calendar] 的全局序列化和反序列化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: ${project.artifactId}
  profiles:
    active: ${profiles.active}
    preview: true
  config:
    import:
      - classpath:config/${spring.profiles.active}/captcha.yml
      - classpath:config/${spring.profiles.active}/doc.yml
      - classpath:config/${spring.profiles.active}/log.yml
      - classpath:config/${spring.profiles.active}/mail.yml
      - classpath:config/${spring.profiles.active}/sso.yml
      - classpath:config/${spring.profiles.active}/tenant.yml
      - classpath:config/${spring.profiles.active}/wx.yml
      - classpath:config/${spring.profiles.active}/xss.yml
      - classpath:config/${spring.profiles.active}/mybatis-plus.yml
  #thymeleaf模板配置
  thymeleaf:
    cache: false                   # 这个开发配置为false，避免改了模板还要重启服务器
    prefix: classpath:/templates/  #模板文件视图前缀，默认是classpath:/templates/，可不用配置
    suffix: .html                  #模板文件视图后缀，默认是.html，可不用配置
    check-template-location: true  #检查模板位置，可不用配置
    encoding: utf-8                #编码字符集，默认为utf-8，可不用配置
    mode: HTML                     #模板的模式，默认为HTML，可不用配置
    servlet:
      content-type: text/html       #模板的内容类型，默认为text/html，可不用配置
  servlet:
    multipart:
      # 单文件大小限制
      max-file-size: 10MB
      # 总上传大小限制
      max-request-size: 10MB
  boot:
    admin:
      client:
        # Admin 服务端地址
        url: ${BREEZE_MONITOR_HOST:http://127.0.0.1:8000}
        # server 用户名
        username: admin
        # server 密码
        password: admin

management:
  #对外开放某个监控点
  endpoint:
    #health必须开
    health:
      show-details: always
      enabled: true
    #其他
    beans:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: false
    # 上报日志到监控 客户端上报日志文件位置
    logfile:
      external-file: ./logs/${spring.application.name}/${spring.application.name}.log

  endpoints:
    #对web开启的监控点
    web:
      exposure:
        include: "*"
    #对外开放所有监控点
    enabled-by-default: true