# spring-mail 相关配置
spring:
  mail:
    # 配置邮件服务器的地址
    host: smtp.qq.com
    # 配置邮件服务器的端口（465或587）
    port: 587
    # 配置用户的账号
    username: 1900381390@qq.com
    # 配置用户的密码（即上面我们申请到的授权码）
    password: szjpgggfodojccah
    # 配置默认编码
    default-encoding: UTF-8
    # SSL 连接配置
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        # 开启 debug，这样方便开发者查看邮件发送日志
        debug: true