breeze:
  aes-secret: 1234567890123456

# sa-token配置
sa-token:
  ignore-urls:
    # Monitor
    - "/actuator/**"
    # Local file storage
    - "/img/**"
    # Data sources & Report generation
    - "/druid/**"
    - "/ureport/**"

  # sso-client 相关配置
  sso-client:
    # sso-server 端主机地址 正式直接使用后端地址，或提前准备好的nginx地址转发
    server-url: http://sa-sso-server.com:9000
    # 使用 Http 请求校验ticket (模式三)
    is-http: true
    # 当前 client 标识
    client: sso-client1
  sign:
    # API 接口调用秘钥
    secret-key: breeze

forest:
  backend: okhttp3             # 后端HTTP框架（默认为 okhttp3）
  max-connections: 1000        # 连接池最大连接数（默认为 500）
  max-route-connections: 500   # 每个路由的最大连接数（默认为 500）
  max-request-queue-size: 100  # [自v1.5.22版本起可用] 最大请求等待队列大小
  max-async-thread-size: 300   # [自v1.5.21版本起可用] 最大异步线程数
  max-async-queue-size: 16     # [自v1.5.22版本起可用] 最大异步线程池队列大小
  connect-timeout: 6000        # 连接超时时间，单位为毫秒（默认为 timeout）
  read-timeout: 3000           # 数据读取超时时间，单位为毫秒（默认为 timeout）
  max-retry-count: 0           # 请求失败后重试次数（默认为 0 次不重试）
  log-enabled: true            # 打开或关闭日志（默认为 true）
  log-request: true            # 打开/关闭Forest请求日志（默认为 true）
  log-response-status: true    # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-content: true   # 打开/关闭Forest响应内容日志（默认为 false）
